# Generated by Django 3.0.1 on 2020-02-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('M_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Food_Name', models.CharField(max_length=50)),
                ('Price', models.IntegerField()),
                ('Image', models.ImageField(default='', upload_to='')),
            ],
            options={
                'db_table': 'Foodie_menu',
            },
        ),
    ]
